<?php echo View::content() ?>

<?php echo Ajax::form('page-wrapper', 'reportes/alumnosporseccion');  ?>
                            <div class="box box-info">
                                     <div class="box-header with-border">
                                            <h4 class="page-head-line">Conceptos de Pago</h4>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Nivel</label>
                                                         <?php echo Conesth::dbselect("codniv","desniv","nivel","",$codniv,"form-control","reportes/alumnosporseccion"); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Curso</label>
                                                         <?php echo Conesth::dbselect("codcur","descur","curso","where codniv='$codniv'",$codcur,"form-control","reportes/alumnosporseccion/".$codniv); ?>
                                                    </div>
                                                </div>
                                                
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Sección</label>
                                                         <?php echo Conesth::dbselect("codsec","codsec","seccion","where codniv='$codniv' and codcur='$codcur'",$codsec,"form-control","reportes/alumnosporseccion/".$codniv."/".$codcur); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Periodo</label>
                                                         <?php echo Conesth::dbselect("codper","codper","periodo","where estado='A'",$codper,"form-control","reportes/alumnosporseccion/".$codniv."/".$codcur."/".$codsec); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 pull-right">
                                                    <?php echo form::hidden("concepto.fecreg"); ?>
                                                     <?php echo Form::submit('Guardar',"class='btn btn-info btn-lg pull-right' name='aceptar'") ?>
                                                </div>
                                            </div>
                                    </div>
                            </div>
  
<?php echo Form::close(); ?>

