<?php echo View::content() ?>

<?php echo Ajax::form('page-wrapper', 'reportes/tot_ing');  ?>
                            <div class="box box-info">
                                     <div class="box-header with-border">
                                            <h4 class="page-head-line">Total Ingresos/Egresos</h4>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Fecha de Inicio</label>
                                                        <?php echo form::text("fecini", "class='form-control'  required placeholder='dd-mm-YYYY'"); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="descripcion">Fecha de Fin</label>
                                                        <?php echo form::text("fecfin", "class='form-control'  required placeholder='dd-mm-YYYY'"); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 pull-right">
                                                    <?php echo form::hidden("factura.fecreg"); ?>
                                                     <?php echo Form::submit('Guardar',"class='btn btn-info btn-lg pull-right' name='aceptar'") ?>
                                                </div>
                                            </div>
                                    </div>
                            </div>
  
<?php echo Form::close(); ?>

