       <?php $cedusu = Session::get('cedusu'); ?>
       <?php $usa=Load::model('usuarios')->busca_uno($cedusu); ?>
     
        <nav class="navbar navbar-default navbar-cls-top hidden-md hidden-sm" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".sidebar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!--<a  class="navbar-brand" href="index1.html">Col. Pequeño Mundo</a>-->
            </div>
           
            <!--<div class="notifications-wrapper hidden-xs">
            <ul class="nav">
                <li class="dropdown pull-right">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user"></i> <?php //echo $usa->nomusu.' '.$usa->apeusu; ?> <i class="fa fa-caret-down"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#"><i class="fa fa-user"></i> Mi Perfil</a>
                        </li>
                        <li class="divider"></li>
                        <li><?php //echo Html::link("", "<i class='fa fa-sign-out'></i> Cerrar Sesión"); ?>
                        </li>
                    </ul>
                </li>
            </ul>
            </div>-->
        </nav>
