 <section class="content hidden-xs">
          <!-- Small boxes (Stat box) -->
          <div class="row">
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-aqua">
                <div class="inner">
                  <h3>Solicitudes</h3>
                  <p>Constancias, Carnets... </p>
                </div>
                <div class="icon">
                  <i class="ion ion-android-checkbox"></i>
                </div>
                <a href="#" class="small-box-footer">Entrar <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            
            <div class="col-lg-3 col-xs-6">
            <!-- small box -->
              <div class="small-box bg-green">
                <div class="inner">
                  <h3> Inscripciones</sup></h3>
                  <p> Inscríbete o Revisa tu Inscripción</p>
                </div>
                <div class="icon">
                  <i class="ion ion-android-create"></i>
                </div>
                <a href="#" class="small-box-footer">Entrar <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
           
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-yellow">
                <div class="inner">
                  <h3>Datos Académicos</h3>
                  <p>Revis tu información académica</p>
                </div>
                <div class="icon">
                  <i class="ion ion-person-add"></i>
                </div>
                <a href="#" class="small-box-footer">Entrar <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
            
            <div class="col-lg-3 col-xs-6">
              <!-- small box -->
              <div class="small-box bg-red">
                <div class="inner">
                  <h3>Retiros</h3>
                  <p>Retira una o todas las materias</p>
                </div>
                <div class="icon">
                  <i class="ion ion-android-close"></i>
                </div>
                <a href="#" class="small-box-footer">Entrar <i class="fa fa-arrow-circle-right"></i></a>
              </div>
            </div><!-- ./col -->
          </div><!-- /.row -->
</section>
