<?php echo View::content(); ?>
<?php if($correc==2){ ?>
	<div class="col-xs-10 col-md-2" align="right">Nombres Correctos: </div>
	<div class="col-xs-10 col-md-3" align="left"><?php echo Form::text("conomest"); ?></div>
    <div class="col-xs-10 col-md-2" align="right">Apellidos Correctos: </div>
    <div class="col-xs-10 col-md-3" align="left"><?php echo Form::text("coapeest") ?></div><br><br>
<?php } ?>