<div class="col-md-10 blogShort paddingTop20">
	<?php echo View::content(); ?>
</div>
                 
<div class="col-md-12 gap10"></div>

    <!--
    <h1>REACTIVADO PROCESO DE EMISIÓN DE CARNETIZACIÓN DE BIBLIOTECA</h1>
    <p class="text-mute">Fecha de Publicación: abril 3, 2016 2:44 pm .</p>
    <hr> 
    	<p class="pull-right"><strong>Publicado en:</strong> Noticias</p>
        <br><br><br>
        <article><p class="text-center">
        	Universidad Nacional Experimental<br>
         	“Francisco de Miranda”<br>
            Vicerrectorado Académico<br>
          	Dirección de Información, Documentación y Biblioteca<br></p>

                           

             <h4>REACTIVADO PROCESO DE EMISIÓN DE CARNETIZACIÓN DE BIBLIOTECA</h4>

             <p class="text-justify">La Dirección de Información, Documentación y Biblioteca de la Universidad Nacional Experimental “Francisco de Miranda”, Unefm.  Hace del conocimiento a la comunidad universitaria,  que a partir de la presente fecha,  se estará realizando el procedimiento normal  de emisión de CARNET DE BIBLIOTECA, tanto a nuevos ingresos como renovaciones.

              	El mismo se lleva a cabo en el edificio “San Gabriel” Antiguo Seminario, calle Zamora esquina calle González, Coro estado Falcón, con un horario  comprendido  de  Lunes  a Viernes  de   8:00 am a 2:00 pm. <br><br><br></p>


                           
             <p class="text-center"><strong>LICDA. YOLIMAR HIGUERA<br>
             	Directora de Información, Documentación y Biblioteca</strong>
             </p> 
          </article>
                
                 </div>
        </div>-->

