    <div >
        
        <div  class="main row">
        	<div  id="estudiantes" class="col-xs-12 col-sm-12 col-md-6 col-lg-5 cont-left">
                    <?php View::content() ?>
		    </div>


             <div class="col-xs-12 col-sm-12 col-md-6 col-lg-7 cont-right">
                <div id="carousel-1" class="carousel slide" data-ride="carousel">

                  <div class="carousel-inner" role="listbox">
                        <div class="item active">
                            <?php echo Html::img('img/slider1.jpg', $alt='User Image', "class='img-responsive'"); ?>
                                <div class="carousel-caption">
                                    <h3> </h3>
                                    <p> </p>
                                </div>
                        </div>
                        <div class="item">
                                <?php echo Html::img('img/slider2.jpg', $alt='User Image', "class='img-responsive'"); ?>

                                <div class="carousel-caption">
                                    <h3> </h3>
                                    <p> </p>
                                </div>
                        </div>
                        <div class="item">
                                <?php echo Html::img('img/slider3.jpg', $alt='User Image', "class='img-responsive'"); ?>

                        <div class="carousel-caption">
                                    <h3> </h3>
                                    <p> </p>
                        </div>
                        </div>
                   </div>
                </div>
            </div>
        </div>
    </div>
