<footer role="contentinfo" id="footerArea" class="footer-base">
    <div class="wrapper wrapper--1-down content-area">
        <a href="#page" class="jump-to-nav jump-to-nav--hidden">
          Jump to Top
        </a>

    <div class="grid grid--footer">
        <div class="w-20 w-33--m">
            <h1 class="footer__heading txt-h5">
              Inscripciones
            </h1>
            <ul ul_attributes="nav-group nav-group--top-bar" display_stickynav="yes" class="list-clean">
                <li class="menu-449 first">
                    <a href="#" title="Nuevos Ingresos">Nuevos Ingresos</a></li>
                <li class="menu-683 last"><a href="#" title="Regulares">Regulares</a></li>
                <li class="menu-683 last"><a href="#" title="Cronogramas">Cronogramas</a></li>
                <li class="menu-683 last"><a href="#" title="Requisitos">Requisitos</a></li>
                <li class="menu-683 last"><a href="#" title="Oferta Académica">Oferta Académica</a></li>
            </ul>
        </div>

        <div class="w-20 w-33--m">
            <h2 class="footer__heading txt-h5">
              Graduaciones
            </h2>
            <ul ul_attributes="nav-group nav-group--top-bar" display_stickynav="yes" class="list-clean">
                <li class="menu-660 first">
                    <a href="/contact-harvard" title="Contact@2">Revisión de Expediente</a></li>
                <li class="menu-2078"><a href="/about-harvard/maps-directions" title="">Solicitud de Grado</a></li>
                <li class="menu-2383"><a href="http://hr.harvard.edu/jobs" title="">Listados Oficiales</a></li>
                <li class="menu-2384 last"><a href="/about-harvard/social-media" title="">Cronogramas</a></li>
            </ul>      
        </div>

      <div class="w-20 w-33--m">
            <h3 class="footer__heading txt-h5">
              Procesos
            </h3>
        <ul ul_attributes="nav-group nav-group--top-bar" display_stickynav="yes" class="list-clean">
            <li class="menu-448 first">
                <a href="/privacy-statement" title="Carnetización">Carnetización</a></li>
            <li class="menu-447"><a href="/copyright-issue" title="Censos">Censos</a></li>
            <li class="menu-861"><a href="/security-issue" title="Revisión de Expediente">Revisión de Expediente</a></li>
        </ul>      
      </div>
      
      <div class="w-20 w-33--m">
            <h3 class="footer__heading txt-h5">
              Soporte
            </h3>
        <ul ul_attributes="nav-group nav-group--top-bar" display_stickynav="yes" class="list-clean">
            <li class="menu-448 first">
                <a href="#" title="Preguntas Frecuentes">Preguntas Frecuentes</a></li>
            <li class="menu-447"><a href="#" title="Contacto">Contacto</a></li>
        </ul>      
      </div>

      <div class="w-footer-last">
        <h4 class="footer__heading txt-h5 is-visually-hidden">
            <br>
            <br>
            <br>
            <br>
        </h4>

        
         <p class="w-60 other-apps">
            <a href="/all-harvard-mobile">
              
            </a>
          </p>
      </div>


    </div> <!-- end footer grid -->

    <p class="footer__outro">
      © 2016 UNEFM - Dirección de Control de Estudios
    </p>

  </div>
</footer>
