<!-- Encabezado -->
            <div class="container-fluid">
                <div class="row">
                    <div class="membrete class col-sm-12">
                      <?php echo Html::img('img/membrete.png', $alt='Membrete', "class='img-responsive hidden-xs'"); ?>
                    </div>
                </div>
            </div>

            <div class="class container-fluid cabecera clearfix">
             <div class="class row">
                <div class="col-xs-12 col-sm-4 col-md-5 col-lg-5 texto-cab visible-lg">
                   <h7 class="">SECRETARÍA <br>
                   <strong>DIRECCIÓN DE CONTROL DE ESTUDIOS</strong></h7>
                </div>
                <div class="col-xs-12 col-sm-8 col-md-7 col-lg-7 visible-lg">
                    <ul id= "iconos">
                        <li id="twitter"><a href="AQUÍ TU ENLACE" title="Síguenos en Twitter"></a> </li>
                        <li id="facebook"><a href="AQUÍ TU ENLACE" title="Síguenos en Facebook"></a></li>
                        <li id="google-plus"><a href="AQUÍ TU ENLACE" title="Conéctate"></a></li>
                        <li id="instagram"><a href="AQUÍ TU ENLACE" title="Síguenos en Instagram"></a></li>
                    </ul>
                 </div>
             </div>
         </div>
