<?php /*  <h1 class="unefm-heading">
    <?php echo Html::link("", "<span class='is-visually-hidden'></span>", "class='unefm-heading__link'"); ?>

    
  </h1>

  <a href="#siteNavigation" class="btn--menu" id="btn_menu" data-state="off" data-id="nav" aria-label="Reveal Navigation">
    <span class="btn--menu__icon"></span>
    Menu
  </a>

    <nav role="navigation" class="main-nav" id="siteNavigation">
          <div class="nav-drawer">
            <div class="nav-group nav-group--consistent">
              <ul class="clearfix">
                <li class="nav-left-half">
                  <ul role="presentation" class="clearfix">
                    <li class="has-drop-nav">
                      <a href="#" class="">INSCRIPCIONES<span class="lg-nav-txt"></span></a>
                        <ul  class="list--drop-nav">
                            <li class="first">
                            <?php echo Ajax::link('descripciones/nuevosingresos', 'Nuevos Ingresos', 'conte','first'); ?>
                            </li>
                            <li class=""><?php echo Ajax::link('descripciones/cronogramas', 'Cronogramas', 'conte'); ?>
                            </li>
                            <li class=""><?php echo Ajax::link("descripciones/requisitos", "Requisitos", 'conte'); ?></li>
                            <li class=""><?php echo Ajax::link("descripciones/ofertaacademica", "Oferta Académica", 'conte'); ?></li>
                        </ul>
                    </li>
                    
                     <li class="has-drop-nav">
                      <a href="#">
                        GRADUACIONES
                        <span class="lg-nav-txt"></span>
                      </a>
                        <ul  class="list--drop-nav">
                            <li class="first"><?php echo Ajax::link('descripciones/revisionexpediente', 'Revisión de Expediente', 'conte','first'); ?></li>
                            <li class="first"><?php echo Ajax::link('descripciones/solicitudgrado', 'Solicitud de Grado', 'conte'); ?></li>
                            <li class=""><?php echo Ajax::link('descripciones/listasoficiales', 'Listados Oficiales', 'conte'); ?></li>
                            <li class=""><?php echo Ajax::link('descripciones/cronogramas', 'Cronogramas', 'conte'); ?></li>
                        </ul>
                      </li>
                  </ul>
                </li>

                <li class="nav-right-half">
                  <ul role="presentation" class="clearfix">
                    <li class="has-drop-nav">
                      <a href="#">
                        PROCESOS
                      </a>

                          <ul  class="list--drop-nav">
                            <li class="first"><?php echo Ajax::link('descripciones/carnet', 'Carnetización', 'conte','first'); ?></li>
                            <li class=""><?php echo Ajax::link('descripciones/censo', 'Censo', 'conte'); ?></li>
                          </ul>
                    </li>
                    <li class="has-drop-nav">
                      <a href="#">
                        SOPORTE
                      </a>
                    	<ul  class="list--drop-nav">
                            <li class="first"><?php echo Ajax::link('descripciones/soporte', 'Contacto', 'conte'); ?></li>
                        </ul>
                    </li>
                  </ul>
                </li>
        
            </div>
        </div>
    </nav> 
*/?>

