<?php echo View::content(); ?>
<br><br>
<p><strong><strong>REQUISITOS PARA NUEVO INGRESO</strong></strong><br>
  -2 fotos tipo carnet<br>
  -1 Fotocopia de la cèdula identidad <br>
  -Original y una copia del Tìtulo de Bachiller<br>
  -Original de la planilla de asignaciòn del CNU sellada<br>
  -Bachillerato fuera del Estado Falcòn traer las notas certificadas por la Zona Educativa <br>
</p>
<p> </p>
<p><strong>DOCUMENTOS A CONSIGNAR PARA LA SOLICITUD DE INGRESO POR EQUIVALENCIA DE BACHILLERES<br>
  </strong>- Comunicación dirigida a la Vicerrectora Académica Prof(a). Olvis Subero de Duran.<strong><br>
  </strong>- Copia de la Cédula de Identidad.<br>
  - Carta original de buena conducta, expedida por la Secretaria de la Institución de procedencia.<br>
  - *Fotocopia del Título de Bachiller.<br>
  - Constancia original de No estar incurso en Sanción Académica emitida por la autoridad competente.<br>
  - Constancia de duración de los periodos académicos en semanas.<br>
  - *Constancias de Notas Certificadas en original de asignaturas Cursadas Aprobadas o No y la escala de calificaciones.<br>
  - Constancia original de Estudios (Si está cursando al momento de solicitar la equivalencia).<br>
  - *Programas de Unidades Curriculares vigentes Cursadas y Aprobadas, debidamente sellados y firmados por la autoridad competente.<br>
  - * Plan de Estudios debidamente firmados y sellados por la autoridad competente.<br>
  - Depósito bancario efectuado en <strong> x x x </strong>a nombre de <strong>Ingresos     Propios UNEFM</strong>, por la cantidad de Bs.F xx. <br>
  * Los documentos deben ser debidamente certificados por la Secretaria de la UNEFM en caso de    presentar copia fotostática. <br>
  <br>
  <strong>REQUISITOS PARA INGRESAR POR EQUIVALENCIAS A LA UNEFM<br>
  </strong>- Cuando el solicitante haya cursado y aprobado todas las   asignaturas del Plan de Estudios, sin haber obtenido el Título   correspondiente, deberá presentar un certificado auténtico y debidamente   legalizado por la Universidad o Institución de Educación Superior donde   terminó sus estudios, haciendo constar que no recibió el título   respectivo.<br>
  <br>
  - Dos o mas programas de asignaturas cursadas y aprobadas por el   solicitante que llenen entre ellos los requisitos del Programa completo   de una asignatura en la Universidad, son válidos para conceder   equivalencias de estudios en esa particular asignatura, pero quedarán   invalidados para cualesquiera otra consideración de equivalencia.<br>
  <br>
  - Los aspirantes deberán tener un promedio de notas acumulado mínimo de   12 puntos o su equivalente en otra escala de calificaciones, de todas   las unidades curriculares aprobadas o no.<br>
  <br>
  - Sólo serán admitidos por equivalencia de estudios aquellos   solicitantes que se les conceda la equivalencia de al menos el 20% del   total de las unidades de crédito del pensum vigente del programa al que   aspiran ingresar.<br>
  <br>
  <strong>NOTA:</strong><strong> <br>
  </strong>Cuando la solicitud es para cambio de programa dentro de   la UNEFM, los solicitantes deberán dirigirse a las respectivas   direcciones de programa. <br>
  <br>
  <strong>*Todo debe venir archivado en un bibliorato o carpeta Mayka </strong><br>
  <br>
  <strong>DOCUMENTOS A CONSIGNAR PARA LA SOLICITUD DE INGRESO POR EQUIVALENCIAS PARA T.S.U.</strong><strong><br>
  </strong>- Comunicación dirigida a la Vicerrectora Académica Prof(a). Olvis Subero de Duran.<br>
  - Copia de la Cédula de Identidad.<br>
  - Carta original de buena conducta, expedida por la Secretaria de la Institución de procedencia.<br>
  - *Fotocopia del Título de T.S.U.<br>
  - Constancia de duración de los periodos académicos en semanas.<br>
  - *Constancias de Notas Certificadas en original de asignaturas Cursadas Aprobadas o No y la escala    de calificaciones.<br>
  - *Programas de Asignaturas   vigentes para el periodo que cursó, sellados y firmados por la autoridad      competente de la Institución de origen.<br>
  - Plan de Estudios firmados y sellados por la autoridad competente de la Institución de origen.<br>
  - Depósito bancario efectuado en <strong> x x x </strong>a nombre de <strong>Ingresos     Propios UNEFM</strong>, por la cantidad de Bs.F xxx. <br>
  * Los documentos deben ser debidamente certificados por la Secretaria de la UNEFM en caso de    presentar copia fotostática. <br>
</p>


