<br><p align="center"><b>OFERTA ACADÉMICA A NIVEL DE PREGRADO</b></p>
<table align="center" border="1" cellpadding="0" cellspacing="0">
  <tbody>
    <tr bgcolor="#3399FF">
      <td><strong>Área de Conocimiento</strong></td>
      <td><strong>Carrera / Programas</strong></td>
      <td><strong>Nivel</strong></td>
      <td><strong>Ubicación</strong></td>
    </tr>
    <tr>
      <td rowspan="11">CIENCIAS DE LA SALUD </td>
      <td>Enfermería</td>
      <td>Técnico Superior</td>
      <td>Anexo   Van Griecken, Unidad Académica Churuguara y en los Municipios:   Carirubana, Silva, Urumaco, Dabajuro , Petit, Bolivar, Unión, Falcón   Colina y el Edo.  Cojedes.</td>
    </tr>
    <tr>
      <td>Medicina</td>
      <td>Licenciatura</td>
      <td>Edif.   Santa Ana / Anexo Van Griecken  y en los Municipios:  Petit, San   Francisco, Monseñor Iturriza, Silva, Democracia, Federación, Carirubana,   Dabajuro</td>
    </tr>
    <tr>
      <td>Gerontología</td>
      <td>Licenciatura (con salida intermedia en T.S.U.)</td>
      <td>Los Borregales y Municipio Dabajuro</td>
    </tr>
    <tr>
      <td>Ingeniería Biomédica</td>
      <td>Licenciatura (con salida intermedia en T.S.U. en Electromedicina)</td>
      <td>Edif. Santa Ana / Van Griecken y Maracay Edo. Aragua</td>
    </tr>
    <tr>
      <td>PNF en Medicina Integral Comunitaria</td>
      <td>Licenciatura</td>
      <td>Calle   Norte, entre Av. Manaure y Calle Toledo y en los Municipios: Mauroa,   Colina, Petit, San Francisco, Monseñor Iturriza, Silva, Democracia,   Federación, Carirubana, Dabajuro</td>
    </tr>
    <tr>
      <td>PNF en Enfermería Integral Comunitaria</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda, Municipio Mauroa, Silva, </td>
    </tr>
    <tr>
      <td>PNF en Fisioterapia</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda, Zamora Falcón, Colina y Morón  </td>
    </tr>
    <tr>
      <td>PNF en Terapia Ocupacional</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda</td>
    </tr>
    <tr>
      <td>PNF en Fonoaudiología</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda</td>
    </tr>
    <tr>
      <td>PNF en Nutrición y Dietética</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda</td>
    </tr>
    <tr>
      <td>PNF en Histocitotecnología</td>
      <td>Licenciatura</td>
      <td>Municipio Miranda</td>
    </tr>
    <tr>
      <td rowspan="6">TECNOLOGÍA</td>
      <td>Ingeniería Civil</td>
      <td>Licenciatura</td>
      <td>C.A.   Los Perozo y en los Municipios: Tocópero, Bolivar, Urumaco, Dabajuro,   Mene Mauroa, Colina, Petit, San Francisco y Monseñor Iturriza,   Democracia, Bolívar, Silva, Carirubana; Zamora, Morón, Unión, Miranda,   Federación, Piritu, Puerto Cabello Manuel Monge Urachiche Iribarren y   Veroes.</td>
    </tr>
    <tr>
      <td>Ingeniería Mecánica</td>
      <td>Licenciatura</td>
      <td>C.A.   El Sabino y en los Municipios: Tocópero, Dabajuro, Mene Mauroa,   Carirubana; Zamora, Morón, Unión,  Federación, Democracia Veroes Manuel   Monge Urachiche, Iribarren y Urumaco</td>
    </tr>
    <tr>
      <td>Ingeniería Industrial</td>
      <td>Licenciatura</td>
      <td>C.A.   El Sabino y en los Municipios: Tocópero, Dabajuro, Silva, Zamora,   Federación, Carirubana, Falcón, Unión, Mene Mauroa, Morón, Veroes,    Manuel Monge Urachiche, Iribarren y Puerto Cabello</td>
    </tr>
    <tr>
      <td>Ingeniería Química</td>
      <td>Licenciatura</td>
      <td>C.A. El Sabino y en los municipios: Falcón, Morón</td>
    </tr>
    <tr>
      <td>Ingeniería Pesquera</td>
      <td>Licenciatura</td>
      <td>Complejo Académico El Sabino</td>
    </tr>
    <tr>
      <td>Ciencias Ambientales</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo y en el Municipio Petit</td>
    </tr>
    <tr>
      <td rowspan="2">CIENCIAS DEL AGRO Y DEL MAR</td>
      <td>Ingeniería Agronómica</td>
      <td>Licenciatura</td>
      <td>C.A.   Ing. Rodolfo J. Bastidas y en los municipios: San Francisco,   Democracia, Federación, Dabajuro, Urumaco, Zamora, Mene Mauroa, Morón,   Urachiche, Veroes  y Bolívar</td>
    </tr>
    <tr>
      <td>Medicina Veterinaria</td>
      <td>Licenciatura</td>
      <td>C.A.   Ing. Rodolfo J. Bastidas y en los municipios: Dabajuro, Mene Mauroa,   San Francisco, Democracia, Bolívar, Zamora, Morón, Unión, Iribarren,   Federación, Falcón, Urachiche, Veroes, Tocópero, Manuel Monge y Morón </td>
    </tr>
    <tr>
      <td rowspan="12">EDUCACIÓN</td>
      <td>Menciones:</td>
      <td> </td>
      <td> </td>
    </tr>
    <tr>
      <td>Agropecuaria</td>
      <td>Licenciatura</td>
      <td>Unidad Acad.Churuguara y en los Municipios: Mene Mauroa, Tocópero</td>
    </tr>
    <tr>
      <td>Lenguas Extranjeras (Inglés)</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo y Municipios: Mauroa, Dabajuro, Urumaco, Carirubana, San Francisco, Tocópero, Morón</td>
    </tr>
    <tr>
      <td>Lengua, Literatura y Latín</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo, C. A. Marino Colina, Unidad Académica Churuguara y Municipios: San Francisco, Dabajuro, Urumaco, Silva, Morón</td>
    </tr>
    <tr>
      <td>Matemática (Informática)</td>
      <td>Licenciatura</td>
      <td>Coro,   C. A. Marino Colina, Unidad Académica Churuguara y Municipios:   Tocópero, Urumaco, Falcón, Silva, San Francisco, Piritu, Unión</td>
    </tr>
    <tr>
      <td>Cs. Sociales mención: Turismo</td>
      <td>Licenciatura</td>
      <td>C.A.   Los Perozo, Unidad Académica Churuguara, C. A. Marino Colina y   municipios: Petit, Carirubana , Silva, San Francisco, Piritu, Tocópero,   Colina, Sucre, Morón</td>
    </tr>
    <tr>
      <td>Educación. Física, Recreación y Entrenamiento Deportivo</td>
      <td>Licenciatura</td>
      <td>C.A.   Los Perozo, C. A. Marino Colina, Unidad Académica Churuguara, Punto   Fijo y municipios: Tocópero, Urumaco, Dabajuro, Mene Mauroa, Colina,   Petit, Urachiche, San Francisco, Monseñor Iturriza, Carirubana, Falcón,   Silva, Piritu, Zamora, Unión, Sucre, Puerto Cabello</td>
    </tr>
    <tr>
      <td>Música</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo y Municipios: Dabajuro, Urumaco, Carirubana, Tocópero </td>
    </tr>
    <tr>
      <td>Desarrollo Empresarial</td>
      <td>Licenciatura</td>
      <td>C.A.   Los Perozos; C.A. Marino Colina y municipios: Tocópero, Dabajuro, San   Francisco, Monseñor Iturriza, Bolívar, Petit, Federación, Colina,   Piritu, Crirubana, Morón, Urumaco, Democracia, Falcón, Silva, Zamora,   Unión, Sucre</td>
    </tr>
    <tr>
      <td>Conservación y Restauración de Bienes Muebles Culturales</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Artes Audiovisuales</td>
      <td>Técnico  Superior</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>PNF en Historia</td>
      <td>Licenciatura</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td colspan="4">Fuente: Dirección de Planificación, Desarrollo y Evaluación - Vicerrectorado Académico (2.015)</td>
    </tr>
  </tbody>
</table>
<p align="center"> <br />
  UNIVERSIDAD NACIONAL EXPERIMENTAL FRANCISCO DE MIRANDA<br />
  OPORTUNIDADES DE ESTUDIOS A NIVEL DE POSTGRADOS</p>
<table align="center" border="1" cellpadding="0" cellspacing="0">
  <tbody>
    <tr>
      <td><strong>Área de Conocimiento</strong></td>
      <td><strong>Postgrado</strong></td>
      <td><strong>Nivel</strong></td>
      <td><strong>Ubicación</strong></td>
    </tr>
    <tr>
      <td rowspan="14">CIENCIAS DE LA SALUD</td>
      <td>Medicina Interna</td>
      <td>Especialización</td>
      <td rowspan="3">Anexo Van Griecken / Santa Ana / Los Perozo  / Ambulatorio San José</td>
    </tr>
    <tr>
      <td>Pediatría y Puericultura</td>
      <td>Especialización</td>
    </tr>
    <tr>
      <td>Ginecología y Obstetricia</td>
      <td>Especialización</td>
    </tr>
    <tr>
      <td>Cirugía General</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Anestesiología</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Medicina Familiar</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Cardiología</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Cirugía Pediátrica</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Neumonología</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Neonatología</td>
      <td>Especialización</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Micología</td>
      <td>Maestría</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Farmacología Sanitaria</td>
      <td>Maestría</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td>Ingeniería Biomédica (Convenio Cuba-Venezuela)</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td> </td>
      <td>Cursos No Conducentes a Grado</td>
      <td>Anexo Van Griecken</td>
    </tr>
    <tr>
      <td rowspan="4">CIENCIAS DEL AGRO Y DEL MAR</td>
      <td>Sistemas de Producción Agrícola en Trópico Seco Mención Producción Vegetal</td>
      <td>Maestría</td>
      <td>C.A. Ing. José Rodolfo Bastidas / C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Sistemas de Producción Agrícola en Trópico Seco Mención Producción Animal</td>
      <td>Maestría</td>
      <td>C.A. Ing. José Rodolfo Bastidas / C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Sanidad Animal</td>
      <td>Maestría</td>
      <td>C.A. Ing. José Rodolfo Bastidas / C.A. Los Perozo</td>
    </tr>
    <tr>
      <td> </td>
      <td>Cursos No Conducentes a Grado</td>
      <td>C.A. Ing. José Rodolfo Bastidas / C.A. Los Perozo</td>
    </tr>
    <tr>
      <td rowspan="14">INGENIERÍA, ARQUITECTURA Y TECNOLOGÍA</td>
      <td>Gerencia Pública</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gerencia de la Calidad y Productividad</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Ingeniería de Procesos</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gerencia de la Construcción</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gerencia de los Proyectos de Ingeniería</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gerencia de Parada de Plantas</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Manejo Integral del Agua (Convenio Cuba-Venezuela)</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Eficiencia Energética (Convenio Cuba-Venezuela)</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Confiabilidad y Mantenimiento Industrial Mención Confiabilidad</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Confiabilidad y Mantenimiento Industrial Mención Mantenimiento Industrial</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Preservaciones de Edificaciones Históricas</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Computación aplicada a la Ingeniería</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Acondicionamiento y Diseño del Patrimonio Histórico y Natural</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td> </td>
      <td>Cursos No Conducentes a Grado</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td rowspan="7">CIENCIAS ECONÓMICAS Y SOCIALES</td>
      <td>Administración de  Empresas Turísticas.</td>
      <td>Especialización Técnica</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Operación  Hotelera y Clubes Recreacionales</td>
      <td>Especialización Técnica</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Planificación Turística.</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gerencia Hotelera</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Museología</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Historia (Convenio UCLA-UNEFM)</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td> </td>
      <td>Cursos No Conducentes a Grado</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td rowspan="8">CIENCIAS DE LA EDUCACIÓN</td>
      <td>Gerencia y Liderazgo Educativo</td>
      <td>Especialización</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Enseñanza de la Matemática Mención Básica, Media y Diversificada</td>
      <td>Especialización</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Enseñanza de la Matemática mención Educación Superior</td>
      <td>Especialización</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Literatura Hispanoamericana</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Gestión y Planificación Deportiva</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Enseñanza de la Lectura y Escritura</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td>Didáctica de la Educación Física (Convenio Cuba-Venezuela)</td>
      <td>Maestría</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td> </td>
      <td>Cursos No Conducentes a Grado</td>
      <td>C.A. Los Perozo</td>
    </tr>
    <tr>
      <td colspan="3">Fuente: Dirección de Planificación, Desarrollo y Evaluación - Vicerrectorado Académico (2.015)</td>
      <td></td>
    </tr>
  </tbody>
</table>
<br><br>
<?php echo View::content(); ?>
