<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Conest2 - Universidad Nacional Experimental Francisco de Miranda</title> 
    <?php Tag::css('login') ?>
    <?php Tag::css('font-awesome/skins/font-awesome') ?>
    <?php Tag::css('style') ?>
    <?php echo Html::includeCss() ?>

    <?php echo Tag::js('js/dist/jquery.min'); ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp'); ?>
    <?php echo Tag::js('jquery/jquery.kumbiaphp.min'); ?>

    
    <link href='https://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>
</head>
<body>
        
<!-- Mixins-->
<!-- Pen Title-->


<div class="container">
  <div class="card"></div>
  <div class="card">
    <?php View::content() ?>
  </div>
  <div class="card alt">
    <div class="toggle"></div>
    <h1 class="title">Registrar
      <div class="close"></div>
    </h1>
    <form>
      <div class="input-container">
        <input type="text" id="Username" required="required"/>
        <label for="Username">Usuario</label>
        <div class="bar"></div>
      </div>
      <div class="input-container">
        <input type="password" id="Password" required="required"/>
        <label for="Password">Contraseña</label>
        <div class="bar"></div>
      </div>
      <div class="input-container">
        <input type="password" id="Repeat Password" required="required"/>
        <label for="Repeat Password">Repetir Contraseña</label>
        <div class="bar"></div>
      </div>
      <div class="button-container">
        <button><span>Siguiente</span></button>
      </div>
    </form>
  </div>
</div>
<!-- Portfolio--><a id="portfolio" href="http://andytran.me/" title="View my portfolio!"><i class="fa fa-link"></i></a>
<!-- CodePen--><a id="codepen" href="http://codepen.io/andytran/" title="Follow me!"><i class="fa fa-codepen"></i></a>
    
       <script type="text/javascript">
        $('.toggle').on('click', function() {
          $('.container').stop().addClass('active');
        });

        $('.close').on('click', function() {
          $('.container').stop().removeClass('active');
        });
    </script>
    
</body>
</html>