
                <form>
                                           
                                            <h4 class="page-head-line"></h4>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="cedula">Codigo</label>
                                                        <input class="form-control" id="numced" placeholder="0103455462006">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="cedula">Número de Cédula</label>
                                                        <input class="form-control" id="numced">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="apellidos">Apellidos</label>
                                                        <input type="text" class="form-control" id="apeest">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="nombres">Nombres</label>
                                                        <input type="email" class="form-control" id="numeest">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="fecha">Fecha de Nacimiento</label>
                                                        <input type="date-time" class="form-control" id="apeest" placeholder="01-01-2016">
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="genero">Género</label>
                                                        <select class="form-control">
                                                            <option>Seleccione...</option>
                                                            <option selected="selected">Masculino</option>
                                                            <option>Femenino</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>
                                            
                                            
                                            <a href="#" class="btn btn-primary">Guardar</a>
                                        </form>