 <div class="row">
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label for="genero">Nivel</label>
                                                        <select class="form-control">
                                                            <option>Seleccione...</option>
                                                            <option selected="selected">Masculino</option>
                                                            <option>Femenino</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label for="genero">Tarifa</label>
                                                        <select class="form-control">
                                                            <option>Seleccione...</option>
                                                            <option selected="selected">Masculino</option>
                                                            <option>Femenino</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label for="genero">Curso</label>
                                                        <select class="form-control">
                                                            <option>Seleccione...</option>
                                                            <option selected="selected">Masculino</option>
                                                            <option>Femenino</option>
                                                        </select>
                                                    </div>
                                                </div>
                                                <div class="col-md-3">
                                                    <div class="form-group">
                                                        <label for="genero">Sección</label>
                                                        <select class="form-control">
                                                            <option>Seleccione...</option>
                                                            <option selected="selected">Masculino</option>
                                                            <option>Femenino</option>
                                                        </select>
                                                    </div>
                                                </div>
                                            </div>