<?php echo View::content() ?>

<?php echo Ajax::form('page-wrapper', 'periodo/actualizacion');  ?>
                            <div class="box box-info">
                                     <div class="box-header with-border">
                                            <h4 class="page-head-line">Período Escolar</h4>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="codigo">Codigo</label>
                                                        <?php echo form::text("codper", "class='form-control'  required",$codper); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">
                                                        <label for="descripcion">Descripción del Nivel</label>
                                                        <?php echo form::text("desper", "class='form-control'  required ",$desper); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="codigo">Fecha de Inicio</label>
                                                        <?php echo form::text("feciniper", "class='form-control'  required placeholder='dd-mm-YYYY'",$feciniper); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="descripcion">Fecha de Fin</label>
                                                        <?php echo form::text("fecfinper", "class='form-control'  required placeholder='dd-mm-YYYY'",$fecfinper); ?>
                                                    </div>
                                                </div>
                                                <div class="col-md-4">
                                                    <div class="form-group">
                                                        <label for="descripcion">Estado</label>
                                                        <?php Conesth::estadoSelect('status', $status); ?>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12 pull-right">
                                                    <?php echo form::hidden("periodo.fecreg"); ?>
                                                     <?php echo Form::submit('Guardar',"class='btn btn-info btn-lg pull-right' name='aceptar'") ?>
                                                </div>
                                            </div>
                                    </div>
                            </div>
  
<?php echo Form::close(); ?>


<br />
<br />
<?php $pagina=Load::model('periodo')->paginar(NULL,$page,$perpage);  ?>

<? if($pagina->total>0) { ?>
<!-- MUESTRA LA PAGINA ACTUAL Y EL TOTAL DE PAGINAS -->

<?php 
if(!isset($show)) {
    $show = 10;
}
    
$half = (int)($show/2);
//echo $halt;
    

if ($pagina->current <= $half) {
    $start = 1;
} elseif (($pagina->total - $pagina->current)<$half) {
    $start = $pagina->total - $show + 1;
} else {
    $start = $pagina->current - $half;
}
?>

<?php if($pagina->prev) echo Ajax::link('periodo/actualizacion/'.$codper.'/N/'.$pagina->prev, Html::img('rewind.png', $alt='Modificar'), 'page-wrapper'); ?>


    <?php for($i=$start; $i<=$pagina->total && $i<($start + $show); $i++): ?>
        <?php echo Ajax::link('periodo/actualizacion/'.$codper.'/N/'.$i, $i , 'page-wrapper'); ?>

    <?php endfor; ?>

<?php if($pagina->next) echo Ajax::link('periodo/actualizacion/'.$codper.'/N/'.$pagina->next, Html::img('fast_forward', $alt='Modificar'), 'page-wrapper'); ?>  

 
<br />

<table class="table table-bordered table-striped table-hover">
<thead>
	<tr>
        <th width="30%" align="left" ><b>Descripción del Nivel </b></th>
        <th width="10%" align="left" ><b>Codigo</b></th>
        <th width="10%" align="left" ><b>Fecha de Inicio</b></th>
        <th width="10%" align="left" ><b>Fecha  de Culminación</b></th>
        <th colspan='2'>-</th>
	</tr>
</thead>
<tbody	
<? foreach($pagina->items as $paginas1): ?> 
    <tr>
        <td align="left" ><?php echo $paginas1->desper ?></td>
        <td align="left" ><?php echo $paginas1->codper ?></td>
         <td align="left" ><?php echo $paginas1->feciniper ?></td>
          <td align="left" ><?php echo $paginas1->fecfinper ?></td>
        <td align="center" ><?php echo Ajax::link('periodo/actualizacion/'.$paginas1->codper.'/N/'.$pagina->current, Html::img('edit.gif', $alt='Modificar'), 'page-wrapper'); ?>
</td>
        <td align="center" ><?php echo Ajax::link('periodo/actualizacion/'.$paginas1->codper.'/E', Html::img('delete.gif', $alt='Eliminar'), 'page-wrapper'); ?></td>
	</tr>
   <? endforeach ?>
  </tbody>
</table>


<br />

<table border="0" cellpadding="1" cellspacing="1" width="80%" align="center">
<tr><td align="right">
   <b>Pág.  </b><?php echo $pagina->current ?> de <?php echo $pagina->total ?>&nbsp;
    </td></tr>
</table>



<? } ?>
